### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ddugovic** [SaxyPandaBear/discord-food-bot#43]
Is this repository available under a free software license to execute, modify, and redistribute?

**Comment by SaxyPandaBear** [comment]
I am mildly perturbed by the number of repositories you have forked, and why you have targeted my side project. I added an AGPL license.

**Comment by ddugovic** [comment]
Many thanks and sorry for any confusion I've caused.

I am a Lichess & Lishogi developer and have collaborated with many amateur developers for fun; but also lately I've been looking for ideas/technologies to present at work (developer meetings).
